name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Depencencies
      run: npm install
    - name: Start App
      run: npm run start &
    
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Depencencies
      run: npm install
    - name: Execute Tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploying to Production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true 
